# Generated by Django 5.0.4 on 2024-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="location",
            new_name="street_name",
        ),
        migrations.AddField(
            model_name="events",
            name="house_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="events",
            name="postal_code",
            field=models.CharField(default="", max_length=6),
        ),
    ]
