# Generated by Django 5.0.4 on 2024-06-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="events",
            name="mage",
            field=models.ImageField(
                default="default_image.jpg", upload_to="event_images"
            ),
        ),
    ]
