# Generated by Django 5.0.4 on 2024-06-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_events_mage_eventimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impressum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
