# Generated by Django 5.0.4 on 2024-06-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_impressum"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="city",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
