# Generated by Django 5.0.4 on 2024-06-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_informationimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="day",
            field=models.CharField(
                choices=[
                    ("Montag", "Montag"),
                    ("Dienstag", "Dienstag"),
                    ("Mittwoch", "Mittwoch"),
                    ("Donnerstag", "Donnerstag"),
                    ("Freitag", "Freitag"),
                    ("Samstag", "Samstag"),
                    ("Sonntag", "Sonntag"),
                ],
                max_length=50,
            ),
        ),
    ]
