# Generated by Django 5.0.4 on 2024-06-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_events_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="impressum",
            name="title",
            field=models.CharField(default="Impressum", max_length=200),
            preserve_default=False,
        ),
    ]
