# Generated by Django 5.0.4 on 2024-06-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_impressum_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impressum",
            name="content",
        ),
        migrations.RemoveField(
            model_name="impressum",
            name="title",
        ),
        migrations.AddField(
            model_name="impressum",
            name="contact_info",
            field=models.TextField(default="", verbose_name="Kontaktinformationen"),
        ),
        migrations.AddField(
            model_name="impressum",
            name="datenschutz",
            field=models.TextField(default="", verbose_name="Datenschutz"),
        ),
        migrations.AddField(
            model_name="impressum",
            name="impressum",
            field=models.TextField(default="", verbose_name="Impressum"),
        ),
        migrations.AddField(
            model_name="impressum",
            name="rechtliche_hinweise",
            field=models.TextField(default="", verbose_name="Rechtliche Hinweise"),
        ),
    ]
