# Generated by Django 5.0.4 on 2024-06-20 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_remove_impressum_content_remove_impressum_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impressum",
            name="rechtliche_hinweise",
        ),
    ]
