# Generated by Django 5.0.4 on 2024-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_remove_impressum_rechtliche_hinweise"),
    ]

    operations = [
        migrations.AddField(
            model_name="impressum",
            name="Geschaeftsführung",
            field=models.TextField(default="", verbose_name="Geschaeftsführung"),
        ),
    ]
