# Generated by Django 5.0.4 on 2024-06-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_impressum_geschaeftsführung"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impressum",
            name="Geschaeftsführung",
        ),
        migrations.AddField(
            model_name="impressum",
            name="Geschaeftsfuehrung",
            field=models.TextField(default="", verbose_name="Geschaeftsfuehrung"),
        ),
    ]
