# Generated by Django 5.0.4 on 2024-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_remove_impressum_geschaeftsführung_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impressum",
            name="Geschaeftsfuehrung",
        ),
        migrations.AddField(
            model_name="impressum",
            name="geschaeftsfuehrung",
            field=models.TextField(default="", verbose_name="geschaeftsfuehrung"),
        ),
    ]
