"""
Django settings for sommer_event project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import requests
#from django.utils.translation import gettext_lazy as _
#import events.translation

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ty(rsvhufls16i^7=^2odew@#=bu+5-@jg)0a2oqtnrk5n0x6o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

try:
    response = requests.get('https://ifconfig.me')
    response.raise_for_status()
    public_ip = response.text.strip()
except requests.RequestException:
    public_ip = None

ALLOWED_HOSTS = ['127.0.0.1','localhost']

CSRF_TRUSTED_ORIGINS = [
    'https://localhost:8000',
    'https://localhost:8001',
]

# Application definition

INSTALLED_APPS = [
    "events",
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sommer_event.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sommer_event.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "de-de"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/workspaces/odinproject/practice/dhl/sommer_event/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images/')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# Date and time formats
DATE_FORMAT = 'd.m.Y'  # Date format for templates and admin
TIME_FORMAT = 'H:i'    # Time format for templates and admin

# Jazzmin settings for customizations
JAZZMIN_SETTINGS = {


    # Other settings...
    "custom_css": "admin/css/custom_admin.css",  # Check path to your custom CSS
    "custom_js": None,  # Ensure no conflicting scripts are causing issues
    #Other settings...

    "site_title": "DHL Admin",
    "site_header": "DHL-Sommerkino Admin",
    "site_brand": "DHL",
    "site_logo": "events/static/images/logo.png",  # Update to correct path
    #"site_copyright": "DHL-Hub Leipzig",
    "site_logo_classes": "img-circle",

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "welcome_sign": " DHL-Sommerkino Admin Panel",
    "hide_apps": [],
    "hide_models": [],
    "custom_links": {
        "auth": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["auth.view_user"]
        }]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "auth"},
    ],
    "custom_css": "admin/css/custom_admin.css",  # Add your CSS file path here
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",  # "single", "horizontal_tabs", "collapsible", "carousel"
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    "site_logo_classes": "img-circle",
    "navbar_fixed": True,
    "navbar_light": True,
    "navbar_color": "navbar-warning",  # Use a Bootstrap class closest to DHL Yellow
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-danger",  # Use a Bootstrap class closest to DHL Red
    "footer_fixed": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "litera",
    "dark_mode_theme": None,
    "navbar": "navbar-warning",
    "sidebar": "sidebar-dark-danger",
    "no_navbar": False,
    "no_sidebar": False,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_small_text": True,
    "footer_fixed": False,
    "body_small_text": True,
    "brand_small_text": False,
    "accent": "accent-danger",
    "navbar_color": "navbar-warning",
    "navbar_classes": "navbar-warning navbar-light",
    "sidebar_classes": "sidebar-dark-danger",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_no_border": False,
    "card_border": False,
    "layout_boxed": False,
    "layout_fixed_footer": False,
}
